apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: openebs
  namespace: kube-system
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: openebs
    version: 1.9.1
  releaseName: openebs
  values:
    localprovisioner:
      basePath: /var/openebs/local
    snapshotOperator:
      enabled: false
    ndm:
      enabled: false
    ndmOperator:
      enabled: false
    analytics:
      enabled: false